### ISSUE TITLE
Error: Proyecto -> Add Project Memeber -> Tabla No encontrada

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/adempiere-grpc-server#520]
Al ejecutar el SB Add Project Member en ventana Proyecto, el mismo da error informando que no logra encontrar la tabla correspondiente.

Se revisa el diccionario y en el SB value=UserBrowser se encuentra que tiene definido el campo AD_Table_ID

Probado en https://vue-develop.solopcloud.com/

Pasos para ejecutarlo

https://github.com/solop-develop/adempiere-grpc-server/assets/14218144/977b90fe-92ee-4d36-b73e-a99f5dfaaf2e

Log del backend

```
===========> ProcessingUserSelection.process: Tabla  * No encontrado * [7616]
org.adempiere.exceptions.AdempiereException: Tabla  * No encontrado *
        at org.compiere.model.PO.getInstances(PO.java:143)
        at org.compiere.process.ProcessInfo.getInstancesForSelection(ProcessInfo.java:776)
        at org.compiere.process.SvrProcess.getInstancesForSelection(SvrProcess.java:533)
        at org.eevolution.project.process.ProcessingUserSelection.doIt(ProcessingUserSelection.java:43)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
        at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:359)
        at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:198)
        at org.eevolution.services.dsl.ProcessBuilder.run(ProcessBuilder.java:223)
        at org.eevolution.services.dsl.ProcessBuilder.lambda$execute$0(ProcessBuilder.java:270)
        at org.compiere.util.Trx.run(Trx.java:529)
        at org.compiere.util.Trx.run(Trx.java:497)

org.adempiere.exceptions.AdempiereException: El proceso falló durante la ejecución Error:  Tabla  * No encontrado *
        at org.eevolution.services.dsl.ProcessBuilder.execute(ProcessBuilder.java:276)
        at org.spin.grpc.service.BusinessDataServiceImplementation.runBusinessProcess(BusinessDataServiceImplementation.java:353)
        at org.spin.grpc.service.BusinessDataServiceImplementation.runBusinessProcess(BusinessDataServiceImplementation.java:205)
        at org.spin.backend.grpc.common.BusinessDataGrpc$MethodHandlers.invoke(BusinessDataGrpc.java:669)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:346)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by rcapecce** [comment]
No sabría, es directamente en el ProcessInfo que la solicita, no llega a ejecutar el proceso

**Comment by EdwinBetanc0urt** [comment]
Fue corregido en el PR https://github.com/solop-develop/adempiere-grpc-server/pull/539 en espera de pruebas.
