### ISSUE TITLE
Error: No permite completar OV por Indice Fuera de Rango

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/adempiere-grpc-server#603]
No se logra completar una OV debido a que informa que el índice está fuera de rango

```
===========> ModelValidationEngine.lambda$fireDocValidate$11: El proceso falló durante la ejecución Error:  The column index is out of range: 1, number of columns
: 0. [1643]
```

Esto puede replicarse en la base demo de spuy que @EdwinBetanc0urt tiene localmente.

**Datos para replicar**

http://host.solopapp.com:24157/ obtener datos de OV 12296 para replicar en instancia de testing, con esta orden fue la prueba que dió este mensajae.

---

```
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.393033469Z -----------> MOrgInfo.get_Value: Column not found - IsExcludeOfCommission [1643]  
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.493001973Z -----------> UpdateProjectProgressLog.doIt: null [1643]                                                                                                           
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.593052281Z -----------> MBPartner.get_Value: Column not found - IsMandatoryOrderReference [1643]                                                                             
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.593098793Z -----------> MOrder.insertTranslations: Table [C_Order_Trl] Not found [1643]                                                                                      
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.793039483Z -----------> MBPartner.get_Value: Column not found - IsMandatoryOrderReference [1643]                                                                
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.793064744Z -----------> MOrgInfo.get_Value: Column not found - IsExcludeOfCommission [1643]     
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.893006613Z -----------> UpdateProjectProgressLog.doIt: null [1643]                       
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.893035908Z -----------> MOrgInfo.get_Value: Column not found - IsExcludeOfCommission [1643]                            
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:56.893043018Z -----------> MSequence.getDocumentNo: No Sequence for DocType - MDocType[1000217-Cálculo de Comisión,DocNoSequence_ID=0] [1643]
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093026627Z ===========> ModelValidationEngine.lambda$fireDocValidate$11: The column index is out of range: 1, number of columns: 0. [1643]
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093059473Z org.adempiere.exceptions.AdempiereException: The column index is out of range: 1, number of columns: 0.
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093067199Z        at org.spin.model.AgencyValidator.lambda$createCommissionForOrder$13(AgencyValidator.java:1513)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093072419Z        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)                            
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093077314Z        at org.spin.model.AgencyValidator.createCommissionForOrder(AgencyValidator.java:1469)     
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093081966Z        at org.spin.model.AgencyValidator.docValidate(AgencyValidator.java:705)                         
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093086288Z        at org.compiere.model.ModelValidationEngine.lambda$fireDocValidate$11(ModelValidationEngine.java:512)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093090601Z        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093131127Z        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)     
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093161706Z        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093168349Z        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093173090Z        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093177419Z        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093181749Z        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093186067Z        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093190353Z        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093194553Z        at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:509)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093198886Z        at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:466)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093202747Z        at org.compiere.model.MOrder.completeIt(MOrder.java:1898)   
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093206968Z        at org.compiere.process.DocumentEngine.completeIt(DocumentEngine.java:537)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093211319Z        at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:322)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093215655Z        at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:296)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093219999Z        at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:267)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093226249Z        at org.compiere.model.MOrder.processIt(MOrder.java:1210)          
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093230612Z        at org.compiere.process.OrderPOCreate.createPOFromSO(OrderPOCreate.java:143)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093239043Z        at org.compiere.process.OrderPOCreate.lambda$doIt$0(OrderPOCreate.java:110)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093244092Z                                                                                                                    
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093244092Z                                                                                                                                                                   
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093248165Z ===========> OrderPOCreate.process: The column index is out of range: 1, number of columns: 0. [1643]
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093252451Z org.adempiere.exceptions.AdempiereException: The column index is out of range: 1, number of columns: 0.
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093256685Z        at org.compiere.model.ModelValidationEngine.lambda$fireDocValidate$11(ModelValidationEngine.java:530)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093261010Z        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093285430Z        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)                                                        
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093291223Z        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)          
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093295672Z        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)  
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093299886Z        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093308898Z        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093313467Z        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093317683Z        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093321812Z        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093326156Z        at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:509)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093330273Z        at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:466)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093334608Z        at org.compiere.model.MOrder.completeIt(MOrder.java:1898)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093338768Z        at org.compiere.process.DocumentEngine.completeIt(DocumentEngine.java:537)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093342916Z        at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:322)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093347191Z        at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:296)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093351328Z        at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:267)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093355582Z        at org.compiere.model.MOrder.processIt(MOrder.java:1210)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093374517Z        at org.compiere.process.OrderPOCreate.createPOFromSO(OrderPOCreate.java:143)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093380531Z        at org.compiere.process.OrderPOCreate.lambda$doIt$0(OrderPOCreate.java:110)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093384966Z 
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093389031Z ===========> ModelValidationEngine.lambda$fireDocValidate$11: El proceso falló durante la ejecución Error:  The column index is out of range: 1, number of columns
: 0. [1643]
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093393936Z org.adempiere.exceptions.AdempiereException: El proceso falló durante la ejecución Error:  The column index is out of range: 1, number of columns: 0.
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093398467Z        at org.eevolution.services.dsl.ProcessBuilder.execute(ProcessBuilder.java:312)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093402612Z        at org.spin.model.AgencyValidator.docValidate(AgencyValidator.java:700)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093406850Z        at org.compiere.model.ModelValidationEngine.lambda$fireDocValidate$11(ModelValidationEngine.java:512)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093411036Z        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093415396Z        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093419726Z        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093430032Z        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093435125Z        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093443773Z        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093448426Z        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093452645Z        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093456864Z        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093461182Z        at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:509)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093465463Z        at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:466)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093475889Z        at org.compiere.model.MOrder.completeIt(MOrder.java:1898)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093481003Z        at org.compiere.process.DocumentEngine.completeIt(DocumentEngine.java:537)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093485223Z        at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:322)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093489483Z        at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:296)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093493710Z        at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:267)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093497917Z        at org.compiere.model.MOrder.processIt(MOrder.java:1210)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093502188Z        at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:861)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093511333Z        at org.compiere.wf.MWFActivity.run(MWFActivity.java:781)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093516384Z        at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093520801Z        at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093525175Z        at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093529493Z        at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093538482Z        at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093543449Z        at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093547712Z        at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093551966Z        at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093556153Z        at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:471)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093564650Z        at org.compiere.wf.MWorkflow.start(MWorkflow.java:736)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093569717Z        at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:798)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093573833Z 
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093577783Z -----------> MWFActivity.run: MWFNode[186-(DocComplete),Action=DocumentAction=CO] [1643]
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093586546Z org.adempiere.exceptions.AdempiereException: El proceso falló durante la ejecución Error:  The column index is out of range: 1, number of columns: 0.
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093601399Z        at org.compiere.model.ModelValidationEngine.lambda$fireDocValidate$11(ModelValidationEngine.java:530)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093606180Z        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093615212Z        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093620386Z        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093624876Z        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093629234Z        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093637905Z        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093642924Z        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093647346Z        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093655980Z        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093661086Z        at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:509)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093665482Z        at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:466)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093674961Z        at org.compiere.model.MOrder.completeIt(MOrder.java:1898)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093679882Z        at org.compiere.process.DocumentEngine.completeIt(DocumentEngine.java:537)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093684165Z        at org.compiere.process.DocumentEngine.prepareThenCompleteIt(DocumentEngine.java:322)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093693049Z        at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:296)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093698133Z        at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:267)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093702535Z        at org.compiere.model.MOrder.processIt(MOrder.java:1210)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093710904Z        at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:861)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093715803Z        at org.compiere.wf.MWFActivity.run(MWFActivity.java:781)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093723987Z        at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093728921Z        at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093739055Z        at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093744040Z        at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093748394Z        at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093756734Z        at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093761751Z        at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093774793Z        at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093779992Z        at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:471)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093784193Z        at org.compiere.wf.MWorkflow.start(MWorkflow.java:736)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093791778Z        at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:798)
docker-compose-adempiere.grpc.server-1  | 2023-11-16T14:48:57.093796647Z 

```

**Comment by EdwinBetanc0urt** [comment]
Se hicieron pruebas con la bases de datos que se envió y no genera error con esa orden de venta, ni con otras existentes o creadas.

Quizás puede ser un model validator.
